module Tactics.SimpleFor1 where

import Types
import Command

-- From real play for problem_1.json
banish1Row :: [Command]
banish1Row = [Move SW,Move E,Move SW,Move E,Move SW,Move SW,Move SW,Move SW,Move E,Move SW,Move SE,Move SE,Move SE,Move SE,Move E,Move E,Move E,Move E,Move SE,Move SE,Move SE,Move SE,Move SW,Move E,Move SW,Move E,Move SW,Move SW,Move SW,Move SW,Move SE,Move SE,Move SE,Move SE,Move SE,Move E,Move E,Move E,Move SE,Move SE,Move SE,Move SE,Move SW,Move E,Move SW,Move E,Move SW,Move SW,Move SW,Move SE,Move SW,Move SE,Move SE,Move SE,Move SE,Move E,Move E,Move SE,Move SE,Move SE,Move SE,Move SW,Move SE,Move SE,Move SE,Move SW,Move SW,Move SW,Move SE,Move SE,Move SE,Move SE,Move E,Move SE,Move SE,Move SE,Move SE,Move SW,Move SE,Move SW,Move SE,Move SW,Move SW,Move SE,Move SE,Move SE,Move SE,Move SE,Move SE,Move SE,Move SE,Move SE,Move SE,Move SW,Move SE,Move SW,Move SW,Move SW,Move SE,Move SE,Move SE,Move SE,Move SW,Move SE,Move SE,Move SE,Move SE,Move SW,Move SW,Move SE,Move SE,Move SW,Move SW,Move SW,Move SE,Move SE,Move SE,Move SE,Move SW,Move SE,Move SE,Move SE,Move SW,Move SW,Move SE,Move SE,Move SW,Move SW,Move SE,Move SE,Move SE,Move SW,Move SW,Move SW,Move SE,Move SE,Move SE,Move SE,Move SW,Move SW,Move SE,Move SE,Move SW,Move SW,Move SE,Move SE,Move SE,Move SW,Move SW,Move SW,Move SW,Move SW,Move SW,Move SW,Move SE,Move SE,Move SW,Move SW,Move SE,Move SE,Move SW,Move SE,Move SW,Move SW,Move SW,Move SW,Move SW,Move SW,Move SW,Move SE,Move SE,Move SW,Move SE,Move SW,Move SE,Move SW,Move SE,Move SW,Move SW,Move W,Move W,Move SW,Move SE,Move SE,Move SW,Move SW,Move SE,Move SE,Move SE,Move SW,Move SW,Move SE,Move SW,Move SE,Move SW,Move W,Move W,Move W,Move SW,Move SW,Move SE,Move SE,Move SW,Move SW,Move SE,Move SE,Move SW,Move SE,Move SW,Move SE,Move SW,Move SE,Move SW,Move W,Move W,Move W,Move SW,Move SW,Move SW,Move SW,Move SW,Move SW,Move SE,Move SE,Move SW,Move SW,Move SE,Move SE,Move SW,Move SE,Move SW,Move W,Move W,Move W,Move SW,Move W,Move SW,Move SW,Move SW,Move SW,Move SE,Move SW,Move SE,Move SE,Move SW,Move SW,Move SE,Move SW,Move SE,Move SW,Move W,Move W,Move W,Move W,Move SW,Move W,Move SW,Move SW,Move SW] ++ banish1Row

player :: IO [Command]
player = return banish1Row
